[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
name = "rattler-build-rebuild"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
rebuild = { cmd = "rattler-build rebuild --package-file ", description = "Rebuilds a package." }
diff = { cmd = "diffoscope", description = "Compares two builds." }

[dependencies]
rattler-build = "0.39.*"
diffoscope = ">=297,<298"
